### ISSUE TITLE
`to_dataset_dict` fails when dataset contains times of mixed types

### ISSUE THREAD

**Issue by alexkjames** [esgf2-us/intake-esgf#73]
**Description:**

When calling `.to_dataset_dict` on a dataset which contains multiple time types, xarray throws an error:

`Cannot combine along dimension 'time' with mixed types.`

and the function fails. Ideally the data wouldn't have this asymmetry, and as such this may be an ESGF/data host problem, not an intake problem. That being said, I thought I'd raise an issue just in case it's something you'd be willing to handle client-side.

**Version:** '2024.10.25'

**Example:**

```
from intake_esgf import ESGFCatalog
cat = ESGFCatalog()
search_result = cat.search(
    experiment_id="midHolocene",
    member_id="r1i1p1f1",
    table_id="Amon",
    source_id="IPSL-CM6A-LR",
    variable_id="tas"
)
search_result.to_dataset_dict()
```

**Comment by nocollier** [comment]
Thank you for this report. I am constantly amazed by how things can fail in ways I never imagined. This is helpful so we can report a more useful message.

**Comment by nocollier** [comment]
It isn't ideal, but I offer a workaround. You can now issue a `paths = search_result.to_path_dict()` and just get the paths returned to you. This would allow you to handle how these are loaded into memory yourself. Perhaps we should consider returning paths if something fails in the `to_dataset_dict()` call?

**Comment by alexkjames** [comment]
Indeed! The joys of data wrangling are multitude. I think the path solution will work nicely for my purposes, thank you!
