### ISSUE TITLE
Code Sprint Ideas

### ISSUE THREAD

**Issue by nocollier** [esgf2-us/intake-esgf#9]
The overarching goal I think would be to make an actual release of `intake-esgf`. I was mistaken about it already existing in PyPI. In my mind, we should:

- [x] Create documentation. My contribution to the cookbook could work as a start. I like [cf-xarray's](https://cf-xarray.readthedocs.io/en/latest/) style. Along the left side I would like to have little snippets that show the different features (basics, esgf1 support, model groups, session logs). I have this started in a [branch](https://github.com/esgf2-us/intake-esgf/tree/doc).
- [x] My progress bars do not always work well in notebooks. I see that there is a `from tqdm.notebook import tqdm_notebook`, but how could I check internally which version to use?
- [x] Setup some process for releases, I like version numbers in the `2024.01` style.
- [x] Setup better testing. I have a couple but they should cover more. 
- [x] Setup CI. Setting it up is not overly hard, but failures could easily be due to server issues. What should be tested and how?
- [x] Code review. I will do a first pass before, but it would be good to step through how it works and if it makes sense the way it is organized.
- [x] Currently I have only tested CMIP6 output, how can we make it work for CMIP5 too? 
- [ ] Enable globus transfers. For this we need to think how this might break the paradigm of how this works. Could we trigger a transfer and then issue a block until the transfer is finished? Does globus give us the tools to make this work? 
- [ ] For non-xarray people, we need a `to_filelist()` operator that will download data and then give you the path of where it is found. This would be useful for me in ILAMB as well.
- [x] Should `intake-esgf` be more formally a `intake` [Catalog](https://intake.readthedocs.io/en/latest/api_base.html#intake.catalog.Catalog)? When I look at their class structure, I am not sure it makes sense, but then I see [intake-esm](https://github.com/intake/intake-esm/blob/main/intake_esm/core.py) implements something. Perhaps it is that intake catalogs do not have such a strict  definition?
- [x] Local database #4 
- [x] Add an issue template for feature requests + bugs

...

**Comment by mgrover1** [comment]
@nocollier - is there anything I can help with this week that would help setup for next week?

**Comment by nocollier** [comment]
I cannot think of anything specific. In my mind we need to setup several things and decide what is in the first version--it is never done of course. I would benefit from talking to someone else who is experience in how things like CI/docs/releases are done to help make decisions. I also would love to have someone else understand the code-base and being able to work on features. That also assumes that you agree/like the way I have organized things.

**Comment by mgrover1** [comment]
Discussions about next steps

## intake-esgf
- [ ] Setup data for testing
- [ ] Expand the search capability
	- [ ] Synonyms, cf-variables, etc.
	- [ ] Project agnostic searches (CMIP5)
- [ ] Globus
	- [ ] transfers
	- [ ] compute
	- [ ] flows

## Cookbooks
- [ ] Publication-focused workflows
	- [ ] Comparing ESGF+ARM data
	- [ ] Reproducing key figures from IPPC report
- [ ] Using with other packages
	- [ ] https://icclim.readthedocs.io/
	- [ ] https://xclim.readthedocs.io/

## WPS
- [ ] Get this running within OLCF/ALCF
